592: idempotency apis
SecureApiGateway/securebanking-openbanking-uk-functional-tests pull request #90
Opened 2023-02-14 12:10 UTC by jorgesanchezperez

- Added new coverage for idempotency apis
Issue: https://github.com/secureapigateway/secureapigateway/issues/592

2023-02-14 12:27 UTC, dbadham-fr requested changes
Can you add some tests which display the idempotent behaviour please?

For example:

1. Same idempotency key is used for same consent request, previously created Consent is returned
2. Same idempotency key is used but consent request is different

2023-02-17 08:17 UTC, jorgesanchezperez commented
> Can you add some tests which display the idempotent behaviour please?
> 
> For example:
> 
> 1. Same idempotency key is used for same consent request, previously created Consent is returned
- Coverage added
> 2. Same idempotency key is used but consent request is different
- Don't make sense because the behaviour still the same even the TPP change the body: "The TPP must not change the request body while using the same x-idempotency-key. If the TPP changes the request body, the ASPSP must not modify the end resource. The ASPSP may treat this as a fraudulent action."

2023-02-17 08:24 UTC, dbadham-fr commented
> > 2. Same idempotency key is used but consent request is different
> 
> * Don't make sense because the behaviour still the same even the TPP change the body: "The TPP must not change the request body while using the same x-idempotency-key. If the TPP changes the request body, the ASPSP must not modify the end resource. The ASPSP may treat this as a fraudulent action."

For me this indicates that the TPP has made a mistake and in an ideal world we would respond with a HTTP 400 Bad Request. As either the TPP is reusing an idempotencyKey within the 24hr window for a different request, or has some bug in their app (or is intentionally trying to do something dodgy).

I think what you have implemented is good enough for v1, I think when we design the solution in the RS / Mongo it would be good to revisit this.

`The ASPSP may treat this as a fraudulent action`, we want to avoid allowing a fraudulent action to return a successful response. However, the OB spec is vague as the use of the word `may` is up for interpretation and the spec doesn't explicitly state what we should do.

2023-02-17 08:25 UTC, dbadham-fr approved these changes

2023-02-17 11:59 UTC, merged